### ISSUE TITLE
How can you load mocha-mongoose once for all of your spec files?

### ISSUE THREAD

**Issue by agconti** [elliotf/mocha-mongoose#13]
You mention in the docs:

> require mocha-mongoose in your spec helper (easier) or in each spec file

What do you mean by spec helper? I've tried to require it via `mocha.opts` but it seems that thats not feasible, see my [SO question](http://stackoverflow.com/questions/29152909/how-can-you-correctly-require-a-module-in-mocha-opts). This was also brought up in #12.

**Comment by elliotf** [comment]
The SO question answered why mocha-mongoose cannot be required as part of mocha's command line `-r` nor via mocha.opts:  `before` is not available at that point.

The way that I organize my tests is to have a spec helper:

https://github.com/elliotf/rssmtp/blob/e027fb97e818db53b6d001f9f2fc558c16f60284/support/spec_helper.js

That gets required in each test file:

https://github.com/elliotf/rssmtp/blob/e027fb97e818db53b6d001f9f2fc558c16f60284/test/routes/index.js#L1

This is a pattern I came to use after being a rails developer for a bit.

Does that make sense?

**Comment by elliotf** [comment]
Note that the project I linked is not using mongodb, but is instead using sequelize.  The DB-clearing code in the spec helper (what mocha-mongoose does) is:

https://github.com/elliotf/rssmtp/blob/e027fb97e818db53b6d001f9f2fc558c16f60284/support/spec_helper.js#L58-L70

I'd recommend using bookshelf.js rather than sequelize if you're contemplating a DB-based ORM.

**Comment by agconti** [comment]
@elliotf thanks for the reply. This really helps;  I wasn't sure what you meant by a spec helper. What do you think about adding these examples to the docs?
